In [14]:
import pandas as pd

In [16]:
# a small function to remove the seconds
def format_twenty_and_nineteen(date):
    date = date[:-3]
    return date

In [17]:
# a small function to format 2018's datetimes
def format_eighteen(date):         
    date = date[0:11] + date[20:-3]
    return date

In [18]:
# a small function to format 2017's datetimes
def format_seventeen(date):
    date = date[:16]
    if 'nan' in date:
        date = date[:10] + ' 00:00:00'
    return date

In [20]:
df_17 = pd.read_csv('raw_data/SF_2017.csv.gz')
df_17.rename({'STOP_FRISK_DATE_STOP_FRISK_TIME' : 'DATE_TIME'}, axis = 1, inplace = True)
df_17['DATE_TIME'] = df_17['DATE_TIME'].map(format_seventeen)
df_17.head()

,DATE_TIME,STOP_FRISK_ID,YEAR2,MONTH2,DAY2,STOP_WAS_INITIATED,RECORD_STATUS_CODE,ISSUING_OFFICER_RANK,ISSUING_OFFICER_COMMAND_CODE,SUPERVISING_OFFICER_RANK,...,STOP_LOCATION_SECTOR_CODE,STOP_LOCATION_APARTMENT,STOP_LOCATION_FULL_ADDRESS,STOP_LOCATION_PREMISES_NAME,STOP_LOCATION_STREET_NAME,STOP_LOCATION_X,STOP_LOCATION_Y,STOP_LOCATION_ZIP_CODE,STOP_LOCATION_PATROL_BORO_NAME,STOP_LOCATION_BORO_NAME
0,2017-01-16 14:25,2017001010001,2017,January,Monday,Based on Self Initiated,APP,SGT,574,SGT,...,(null),(null),180 GREENWICH STREET,(null),GREENWICH STREET,982381.0,201750.0,(null),PBMS,MANHATTAN
1,2017-01-16 14:25,2017001010002,2017,January,Monday,Based on Self Initiated,APP,SGT,574,SGT,...,(null),(null),180 GREENWICH STREET,(null),GREENWICH STREET,982381.0,201750.0,(null),PBMS,MANHATTAN
2,2017-02-08 11:09,2017001010005,2017,February,Wednesday,Based on C/W on Scene,APP,POM,863,SGT,...,C,(null),WALL STREET && BROADWAY,(null),WALL STREET,981005.0,197131.0,(null),PBMS,MANHATTAN
3,2017-02-20 11:34,2017001010006,2017,February,Monday,Based on Self Initiated,APP,POM,1,SGT,...,H,(null),75 GREENE STREET,(null),GREENE STREET,984031.0,202796.0,(null),PBMS,MANHATTAN
4,2017-02-21 13:20,2017001010007,2017,February,Tuesday,Based on Radio Run,APP,POM,1,SGT,...,H,2,429 WEST BROADWAY,(null),WEST BROADWAY,983894.0,203523.0,(null),PBMS,MANHATTAN

In [22]:
df_18 = pd.read_csv('raw_data/SF_2018.csv.gz')
df_18.rename({'STOP_FRISK_DATE_Stop Frisk Time' : 'DATE_TIME'}, axis = 1, inplace = True)
df_18['DATE_TIME'] = df_18['DATE_TIME'].map(format_eighteen)
df_18.head()

,DATE_TIME,STOP_FRISK_ID,YEAR2,MONTH2,DAY2,STOP_WAS_INITIATED,RECORD_STATUS_CODE,ISSUING_OFFICER_RANK,ISSUING_OFFICER_COMMAND_CODE,SUPERVISING_OFFICER_RANK,...,STOP_LOCATION_SECTOR_CODE,STOP_LOCATION_APARTMENT,STOP_LOCATION_FULL_ADDRESS,STOP_LOCATION_PREMISES_NAME,STOP_LOCATION_STREET_NAME,STOP_LOCATION_X,STOP_LOCATION_Y,STOP_LOCATION_ZIP_CODE,STOP_LOCATION_PATROL_BORO_NAME,STOP_LOCATION_BORO_NAME
0,2018-01-01 19:04,1,2018,January,Monday,Based on C/W on Scene,APP,POM,1,SGT,...,G,(null),VARICK STREET && FRANKLIN STREET,(null),VARICK STREET,982327,201274,(null),PBMS,MANHATTAN
1,2018-01-01 23:00,2,2018,January,Monday,Based on Radio Run,APP,POM,34,SGT,...,C,(null),DYCKMAN STREET && POST AVENUE,(null),DYCKMAN STREET,1004892,253548,(null),PBMN,MANHATTAN
2,2018-01-01 23:55,3,2018,January,Monday,Based on Radio Run,APP,POM,808,SGT,...,B,4M,2245 RANDALL AVENUE,(null),RANDALL AVENUE,1026706,237776,(null),PBBX,BRONX
3,2018-01-01 03:23,4,2018,January,Monday,Based on Radio Run,APP,POM,63,SGT,...,B,(null),EAST 38 STREET && AVENUE L,(null),EAST 38 STREET,1001347,166195,(null),PBBS,BROOKLYN
4,2018-01-01 03:23,5,2018,January,Monday,Based on Radio Run,APP,POM,63,SGT,...,B,(null),EAST 38 STREET && AVENUE L,(null),EAST 38 STREET,1001347,166195,(null),PBBS,BROOKLYN

In [23]:
df_19 = pd.read_csv('raw_data/SF_2019.csv.gz')
df_19.rename({'STOP_FRISK_DATE_STOP_FRISK_TIME' : 'DATE_TIME'}, axis = 1, inplace = True)
df_19['DATE_TIME'] = df_19['DATE_TIME'].map(format_twenty_and_nineteen)
df_19.head()

,DATE_TIME,STOP_ID_ANONY,YEAR2,MONTH2,DAY2,STOP_WAS_INITIATED,RECORD_STATUS_CODE,ISSUING_OFFICER_RANK,ISSUING_OFFICER_COMMAND_CODE,SUPERVISING_OFFICER_RANK,...,STOP_LOCATION_PRECINCT,STOP_LOCATION_SECTOR_CODE,STOP_LOCATION_APARTMENT,STOP_LOCATION_FULL_ADDRESS,STOP_LOCATION_STREET_NAME,STOP_LOCATION_X,STOP_LOCATION_Y,STOP_LOCATION_ZIP_CODE,STOP_LOCATION_PATROL_BORO_NAME,STOP_LOCATION_BORO_NAME
0,2019-01-02 14:30,1,2019,January,Wednesday,Based on C/W on Scene,APP,POM,1,SGT,...,1,C,(null),230 VESEY STREET,VESEY STREET,979667,199737,(null),PBMS,MANHATTAN
1,2019-01-08 02:30,2,2019,January,Tuesday,Based on Self Initiated,APP,POM,1,SGT,...,1,C,(null),9 WHITE STREET,WHITE STREET,982650,201326,(null),PBMS,MANHATTAN
2,2019-01-12 16:54,3,2019,January,Saturday,Based on Radio Run,APP,POM,1,SGT,...,1,D,(null),131 SPRING STREET,SPRING STREET,984063,203033,(null),PBMS,MANHATTAN
3,2019-01-14 21:21,4,2019,January,Monday,Based on Radio Run,APP,POM,1,SGT,...,1,(,(null),GRAND STREET && 6TH AVE,GRAND STREET,982848,202677,(null),PBMS,MANHATTAN
4,2019-01-15 18:50,5,2019,January,Tuesday,Based on Radio Run,APP,POM,1,SGT,...,1,D,(null),32 THOMPSON STREET,THOMPSON STREET,983100,202705,(null),PBMS,MANHATTAN

In [24]:
df_20 = pd.read_csv('raw_data/SF_2020.csv.gz')
df_20.rename({'STOP_FRISK_DATE_STOP_FRISK_TIME' : 'DATE_TIME'}, axis = 1, inplace = True)
df_20['DATE_TIME'] = df_20['DATE_TIME'].map(format_twenty_and_nineteen)
df_20.head()

,DATE_TIME,STOP_ID,YEAR2,MONTH2,DAY2,STOP_WAS_INITIATED,RECORD_STATUS_CODE,ISSUING_OFFICER_RANK,ISSUING_OFFICER_COMMAND_CODE,SUPERVISING_OFFICER_RANK,...,STOP_LOCATION_PRECINCT,STOP_LOCATION_SECTOR_CODE,STOP_LOCATION_APARTMENT,STOP_LOCATION_FULL_ADDRESS,STOP_LOCATION_STREET_NAME,STOP_LOCATION_X,STOP_LOCATION_Y,STOP_LOCATION_ZIP_CODE,STOP_LOCATION_PATROL_BORO_NAME,STOP_LOCATION_BORO_NAME
0,2020-01-01 01:12,1,2020,January,Wednesday,Based on Radio Run,APP,POM,19,SGT,...,19,C,(null),248 E 83 ST,E 83 ST,997094,222002,10028,PBMN,MANHATTAN
1,2020-01-01 01:11,2,2020,January,Wednesday,Based on Radio Run,APP,POM,19,SGT,...,19,C,(null),248 E 83 ST,E 83 ST,997094,222002,10028,PBMN,MANHATTAN
2,2020-01-01 01:11,3,2020,January,Wednesday,Based on Radio Run,APP,POM,19,SGT,...,19,C,(null),248 E 83 ST,E 83 ST,997094,222002,10028,PBMN,MANHATTAN
3,2020-01-01 10:18,4,2020,January,Wednesday,Based on Radio Run,APP,POM,75,LT,...,75,D,(null),LINDEN BLVD && SHEPHERD AVE,LINDEN BLVD,1018441,181412,11208,PBBN,BROOKLYN
4,2020-01-01 08:45,5,2020,January,Wednesday,Based on Radio Run,APP,POM,78,SGT,...,78,B,(null),481 5 AVE,5 AVE,987763,182543,11215,PBBS,BROOKLYN

In [25]:
df_21 = pd.read_csv('raw_data/SF_2021.csv.gz')
df_21.rename({'STOP_FRISK_DATE_STOP_FRISK_TIME' : 'DATE_TIME'}, axis = 1, inplace = True)
df_21['DATE_TIME'] = df_21['DATE_TIME'].map(format_twenty_and_nineteen)
df_21.head()

/Users/b0ihazard/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,DATE_TIME,STOP_ID,YEAR2,MONTH2,DAY2,STOP_WAS_INITIATED,RECORD_STATUS_CODE,ISSUING_OFFICER_RANK,ISSUING_OFFICER_COMMAND_CODE,SUPERVISING_OFFICER_RANK,...,SUSPECT_OTHER_DESCRIPTION,STOP_LOCATION_PRECINCT,STOP_LOCATION_SECTOR_CODE,STOP_LOCATION_APARTMENT,STOP_LOCATION_FULL_ADDRESS,STOP_LOCATION_STREET_NAME,STOP_LOCATION_X,STOP_LOCATION_Y,STOP_LOCATION_PATROL_BORO_NAME,STOP_LOCATION_BORO_NAME
0,2021-01-01 01:50,1,2021,January,Friday,Based on C/W on Scene,APP,SGT,42,POM,...,(null),42,B,2C,850 JENNINGS ST,JENNINGS ST,1013737,242476,PBBX,BRONX
1,2021-01-01 10:55,2,2021,January,Friday,Based on Radio Run,APP,POM,105,SGT,...,NaN,105,B,(null),219 ST && 139 AVE,219 ST,1052511,184460,PBQS,QUEENS
2,2021-01-01 10:10,3,2021,January,Friday,Based on C/W on Scene,APP,POM,106,SGT,...,YELLOW SWEATER,106,A,(null),151 AVE && 84 ST,151 AVE,1025662,182632,PBQS,QUEENS
3,2021-01-01 20:17,4,2021,January,Friday,Based on C/W on Scene,APP,POM,83,LT,...,(null),73,A,(null),BROADWAY && MAC DOUGAL ST,BROADWAY,1010122,187312,PBBN,BROOKLYN
4,2021-01-01 19:59,5,2021,January,Friday,Based on Radio Run,APP,POM,26,SGT,...,UNKNOWN,26,C,4D,439 W 125 ST,W 125 ST,996623,235311,PBMN,MANHATTAN